### ISSUE TITLE
inventario

### ISSUE THREAD

**Issue by maticati** [hermanfenderson/BrucaBook#128]
bla bla

**Comment by hermanfenderson** [comment]
ci lavoro su a partire dalla versione 0.4.0

**Comment by hermanfenderson** [comment]
Ciao!
L'inventario è stato rilasciato. 
In produzione c'e' la versione 0.4.3.
Provalo!
Usa la voce "inventario" e carica manualmente i libri oppure premi il tasto carica e carica in automatico tutto il magazzino...
